spring:
  datasource:
    url: jdbc:h2:file:./mankoff_bank_db
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
dz9:
  currency: EUR
  USD: 1
  RUB: 70
  EUR: 1.1

app:
  currency: RUB
  USD: 1
  RUB: 70
  EUR: 1.1
  jsonName: ustinoff